In [2]:
import pickle

with open("s01.dat", "rb") as f:
    data = pickle.load(f, encoding="latin1")

print(type(data))
print(data.keys())

<class 'dict'>
dict_keys(['labels', 'data'])


In [3]:
print("Data shape :", data["data"].shape)
print("Labels shape:", data["labels"].shape)

Data shape : (40, 40, 8064)
Labels shape: (40, 4)


In [4]:
print(data["data"].dtype)
print(data["labels"].dtype)

float64
float64


In [5]:
print(data["labels"][:5])

[[7.71 7.6  6.9  7.83]
 [8.1  7.31 7.28 8.47]
 [8.58 7.54 9.   7.08]
 [4.94 6.01 6.12 8.06]
 [6.96 3.92 7.19 6.05]]


In [6]:
import numpy as np

labels = data["labels"]

print("Minimum")
print(labels.min(axis=0))

print("\nMaximum")
print(labels.max(axis=0))

print("\nMean")
print(labels.mean(axis=0))

Minimum
[1.36 2.08 2.04 3.87]

Maximum
[9.   8.15 9.   8.47]

Mean
[5.11775 5.65975 5.9025  6.84675]


In [7]:
import glob
import pickle
import numpy as np

all_labels = []

for file in sorted(glob.glob("s*.dat")):
    with open(file, "rb") as f:
        d = pickle.load(f, encoding="latin1")
        all_labels.append(d["labels"])

all_labels = np.concatenate(all_labels)

print("Shape:", all_labels.shape)
print("Minimum:", all_labels.min(axis=0))
print("Maximum:", all_labels.max(axis=0))
print("Mean:", all_labels.mean(axis=0))

Shape: (1280, 4)
Minimum: [1. 1. 1. 1.]
Maximum: [9. 9. 9. 9.]
Mean: [5.2543125  5.15671094 5.38275    5.51813281]


In [8]:
valence = all_labels[:, 0]

y = (valence > 5).astype(int)

print(np.bincount(y))

[572 708]


In [9]:
print(data["data"].shape)

(40, 40, 8064)


In [10]:
eeg = data["data"][:, :32, :]
print(eeg.shape)

(40, 32, 8064)


In [11]:
import glob
import pickle
import numpy as np

for file in sorted(glob.glob("s*.dat")):
    with open(file, "rb") as f:
        d = pickle.load(f, encoding="latin1")

    eeg = d["data"][:, :32, :]

    print(
        file,
        eeg.shape,
        np.isnan(eeg).sum(),
        np.isinf(eeg).sum()
    )

s01.dat (40, 32, 8064) 0 0
s02.dat (40, 32, 8064) 0 0
s03.dat (40, 32, 8064) 0 0
s04.dat (40, 32, 8064) 0 0
s05.dat (40, 32, 8064) 0 0
s06.dat (40, 32, 8064) 0 0
s07.dat (40, 32, 8064) 0 0
s08.dat (40, 32, 8064) 0 0
s09.dat (40, 32, 8064) 0 0
s10.dat (40, 32, 8064) 0 0
s11.dat (40, 32, 8064) 0 0
s12.dat (40, 32, 8064) 0 0
s13.dat (40, 32, 8064) 0 0
s14.dat (40, 32, 8064) 0 0
s15.dat (40, 32, 8064) 0 0
s16.dat (40, 32, 8064) 0 0
s17.dat (40, 32, 8064) 0 0
s18.dat (40, 32, 8064) 0 0
s19.dat (40, 32, 8064) 0 0
s20.dat (40, 32, 8064) 0 0
s21.dat (40, 32, 8064) 0 0
s22.dat (40, 32, 8064) 0 0
s23.dat (40, 32, 8064) 0 0
s24.dat (40, 32, 8064) 0 0
s25.dat (40, 32, 8064) 0 0
s26.dat (40, 32, 8064) 0 0
s27.dat (40, 32, 8064) 0 0
s28.dat (40, 32, 8064) 0 0
s29.dat (40, 32, 8064) 0 0
s30.dat (40, 32, 8064) 0 0
s31.dat (40, 32, 8064) 0 0
s32.dat (40, 32, 8064) 0 0


In [12]:
label_names = ["Valence", "Arousal", "Dominance", "Liking"]

for i, name in enumerate(label_names):

    print("="*40)
    print(name)

    print("Minimum :", all_labels[:, i].min())
    print("Maximum :", all_labels[:, i].max())
    print("Mean    :", all_labels[:, i].mean())

Valence
Minimum : 1.0
Maximum : 9.0
Mean    : 5.2543125
Arousal
Minimum : 1.0
Maximum : 9.0
Mean    : 5.1567109375
Dominance
Minimum : 1.0
Maximum : 9.0
Mean    : 5.38275
Liking
Minimum : 1.0
Maximum : 9.0
Mean    : 5.5181328125


In [13]:
# Count how many values are below 1 in each label

for i, name in enumerate(label_names):

    count = np.sum(all_labels[:, i] < 1)

    print(f"{name}: {count} values below 1")

Valence: 0 values below 1
Arousal: 0 values below 1
Dominance: 0 values below 1
Liking: 0 values below 1


In [14]:
# Extract Valence labels

valence = all_labels[:, 0]

# Convert into binary classes
# High Valence (>5) -> 1
# Low Valence (<=5) -> 0

y = (valence > 5).astype(int)

print("Class Distribution:")
print(np.bincount(y))

# If the dataset is balanced, both classes should be reasonably close.

Class Distribution:
[572 708]


In [15]:
print("Minimum Valence :", valence.min())
print("Maximum Valence :", valence.max())
print("Mean Valence    :", valence.mean())

Minimum Valence : 1.0
Maximum Valence : 9.0
Mean Valence    : 5.2543125


In [16]:
invalid = all_labels[all_labels[:, 0] < 1]

print(invalid)

[]
